/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_virtushawk_app_jni_JNIApplication */

#ifndef _Included_com_virtushawk_app_jni_JNIApplication
#define _Included_com_virtushawk_app_jni_JNIApplication
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_virtushawk_app_jni_JNIApplication
 * Method:    sum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_virtushawk_app_jni_JNIApplication_sum
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
